### ISSUE TITLE
loading vtk

### ISSUE THREAD

**Issue by lebrat** [ilwoolyu/LocalGyrificationIndex#2]
Hello,
I am using the cmorph docker version of LGI, I have the following error message using freesurfer pial meshes
```
read vtk: input.vtk
Error using dataread
Buffer overflow (bufsize = 4095) while reading string from
file (row 2957, field 1). Use 'bufsize' option. See HELP TEXTREAD.
Error in textread (line 176)
Error in read_vtk (line 6)
Error in OuterHull (line 18)
MATLAB:dataread:BufferOverload
```
I have tried to down-size the input mesh with meshlab (30k faces) and I still have the same issue.

Thanks for your help and for _dockering_ those tools :+1:

**Comment by ilwoolyu** [comment]
Hi,

Thanks for your interest in my tool and reporting this. It's likely because the vtk file contains too many characters in a single line(s), which was not properly handled in matlab; the buffer size is less than 4096 by default. I will fix the issue in the next release. Alternatively, if you use freesurfer's ``mris_convert <in_mesh> <out_mesh.vtk>``, it will automatically break the lines per vertex/face.

**Comment by lebrat** [comment]
Hello,
Many thanks for your quick answer, your work and docker are really appreciated. Your solution work just fine with Freesurfer meshes, but in my project, I will use .stl stemming from different softwares.
I tried `mris_convert` `meshio-convert` and `vtk` (python version) to convert my input meshes in the .vtk format but it did not work. 

Any pointer on how to tweak this buffer size argument?
I will try harder tomorrow, if I have any success I will update you.

Cheers,
Leo.

**Comment by ilwoolyu** [comment]
Leo, could you share what you converted into vtk if possible? Thanks!

**Comment by lebrat** [comment]
Hello,
Unfortunately, I cannot share human data... 
I have sent you my conversion script for .stl and .obj; feel free to include it in the repo.
Again thank you for your time and your help.

:wq
Leo.
