### ISSUE TITLE
Error using sscanf Not enough input arguments.

### ISSUE THREAD

**Issue by LucasFidon** [ilwoolyu/LocalGyrificationIndex#3]
Hi, thank you for sharing your great work!

I am trying to run your code and I am running into a problem.
Your help to understand what is wrong would be much appreciated.

I run this command:
docker run -v \<MY-LOCAL-FOLDER-PATH\>:/INPUT/ --rm ilwoolyu/cmorph:1.7 lgi -i /INPUT/pial.vtk

And I obtain the following logs:

rm -Rf /opt/cmorph/tmp-lgi-pial

mkdir -p /opt/cmorph/tmp-lgi-pial

/opt/cmorph/bin/OuterHull /INPUT/pial.vtk /opt/cmorph/tmp-lgi-pial/pial.hull.vtk

read vtk: /INPUT/pial.vtk
Error using sscanf
Not enough input arguments.

Error in read_vtk (line 16)

Error in OuterHull (line 18)

MATLAB:minrhs
ERROR: /opt/cmorph/bin/OuterHull /INPUT/pial.vtk /opt/cmorph/tmp-lgi-pial/pial.hull.vtk failed!

Thanks,
Lucas

**Comment by ilwoolyu** [comment]
Hi Lucas,

I suspect two issues that might occur in your command line.

1) in docker, you miss your local folder before ":/INPUT/". You need to provide -v **[full_path_of_your_local_folder_to_vtk]:**/INPUT
2) if your VTK file was generated by the latest VTK library (v9), the format is not supported because of some extra fields introduced in the new format.

Could you please check them first?

Ilwoo

**Comment by LucasFidon** [comment]
Hi Ilwoo,

Thank you for the quick reply!
1. Sorry, it was due to an error when writing my first message above (corrected now)
2. The vtk files I have use vtk DataFile Version 4.0

I have been able to reproduce the same error using a volume from a public fetal brain atlas [1].
You can find the input pial.vtk and wm.vtk here 
https://drive.google.com/drive/folders/1rCK8upuCEJRQxI9X2VhJEcGsQJpFkBmj?usp=sharing

Thank you for your help,
Lucas

[1] https://www.synapse.org/#!Synapse:syn25887675/wiki/611424 
(I have used the template volume fetal_SB_atlas_GA25_operated)

**Comment by ilwoolyu** [comment]
Hi Lucas,

Thanks for sharing your data. I found issues on the files.

1. VTK data format (>v4.0) is not supported because it has changed triangle representations, so my current implementation can read only the legacy format (v1.0-v3.0). The old VTK library (v5.0-v8.0) read that format and can support a legacy data format. The latest VTK library may support the legacy formats as I checked their community had an open issue about version support but not sure if that functionality is incorporated in their current release.
2. Your mesh files look not like fully closed hemispheres. I see a bunch of isolated regions. You need a good quality of cortical surfaces such as FreeSurfer - we need to see clear sulcal and gyral patterns in visual inspection. Plus, my tool works best on a single hemisphere though you can provide whole brain as a single mesh - in this case, you will see unexpected gyrification around deep valley between two hemispheres.

Ilwoo

**Comment by LucasFidon** [comment]
Hi Ilwoo,

Sorry for the late reply.
I wanted to give you an update on my experiments with your code.

I have found that your code works on our fetal MRI data with:
- ilwoolyu/cmorph:1.7
- python3.6
- vtk v8.1.2 (which saves .vtk files with vtk DataFile Version 4.2)

I have used a kernel size of 108 like in your experiments on neonats.

I have checked the results qualitatively by visualizing the LGI maps on the cortex surface using vtk.

I have successfully computed the LGIs for more than 100 fetal brains for which we have a 3D reconstructed MRI, and manual segmentation for the white matter and the cortical gray matter.

Thank you for sharing your code and for your help,
Lucas
